packages:
  - core
  - packages/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@vercel/speed-insights'
  - esbuild
  - msw
  - puppeteer
  - sharp

patchedDependencies:
  '@opennextjs/cloudflare@1.6.5': packages/cli/patches/@opennextjs__cloudflare@1.6.5.patch

publicHoistPattern:
  - '@bigcommerce/eslint-*'
  - '@bigcommerce/eslint-*'
  - '@next/eslint-*'
  - '@stylistic/eslint-*'
  - '@typescript-eslint/*'
  - eslint-config-*
  - eslint-plugin-*
